# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: wckansai.dev
ip: 192.168.33.10

#
# WordPress Settings
#
version: latest
lang: ja

plugins:
  - wp-multibyte-patch
